export const PAGINATION = {
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 50,
} as const;

export const VALIDATION_LIMITS = {
  POST_TITLE_MAX: 200,
  POST_EXCERPT_MAX: 500,
  POST_CONTENT_MAX: 50_000,

  BIKE_NAME_MAX: 100,
  BIKE_BRAND_MAX: 100,
  BIKE_MODEL_MAX: 100,
  BIKE_DESCRIPTION_MAX: 2000,
  BIKE_YEAR_MIN: 1900,

  COMPONENT_NAME_MAX: 100,
  COMPONENT_BRAND_MAX: 100,
  COMPONENT_MODEL_MAX: 100,
  COMPONENT_NOTES_MAX: 2000,

  MAINTENANCE_TITLE_MAX: 200,
  MAINTENANCE_DESCRIPTION_MAX: 5000,

  TAG_NAME_MAX: 50,

  USER_DISPLAY_NAME_MAX: 100,
  USER_BIO_MAX: 500,
} as const;

export const IMAGE_MAX_SIZE_BYTES = 5 * 1024 * 1024; // 5 MB

export const ALLOWED_IMAGE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
] as const;
